name: Build assets

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      store:
        required: false
        type: boolean
        default: false
      php-install:
        required: false
        type: boolean
        default: false
      php-version:
        required: false
        type: string
        default: ''
    outputs:
      commit:
        description: The commit hash of the build
        value: ${{ jobs.build.outputs.commit }}
      version:
        description: The version of the build
        value: ${{ jobs.build.outputs.version }}
      release:
        description: The release of the build
        value: ${{ jobs.build.outputs.release }}

jobs:
  #############
  # Build
  #############
  build:
    runs-on: ubuntu-latest
    name: Build assets
    outputs:
      commit: ${{ steps.js.outputs.commit }}
      version: ${{ steps.js.outputs.version }}
      release: ${{ steps.js.outputs.release }}

    strategy:
      fail-fast: false

    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install php dependencies
        uses: monicahq/workflows/.github/actions/php@v3
        if: inputs.php-install
        with:
          php-version: ${{ php-version }}

      - name: Build javascript assets
        uses: monicahq/workflows/.github/actions/js@v3
        id: js
        with:
          node-version: ${{ inputs.node-version }}
          mock-assets: ${{ inputs.mock-assets }}

      - name: Store assets
        if: inputs.store
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: |
            public/build/**/*
            !public/build/**/*.map
          overwrite: true

      - name: Store source maps
        if: inputs.store
        uses: actions/upload-artifact@v4
        with:
          name: sourcemaps
          path: |
            public/build/**/*.map
          overwrite: true
