name: Build assets

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      store:
        required: false
        type: boolean
        default: false
    outputs:
      commit:
        description: The commit hash of the build
        value: ${{ jobs.build.outputs.commit }}
      version:
        description: The version of the build
        value: ${{ jobs.build.outputs.version }}
      release:
        description: The release of the build
        value: ${{ jobs.build.outputs.release }}

jobs:
  #############
  # Build
  #############
  build:
    runs-on: ubuntu-latest
    name: Build assets
    outputs:
      commit: ${{ steps.js.outputs.commit }}
      version: ${{ steps.js.outputs.version }}
      release: ${{ steps.js.outputs.release }}

    strategy:
      fail-fast: false

    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - uses: ./.github/actions/js
        id: js
        with:
          node-version: ${{ inputs.node-version }}
          mock-assets: ${{ inputs.mock-assets }}

      - name: Store assets
        if: inputs.store
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: |
            public/build/**/*
            !public/build/**/*.map

      - name: Store source maps
        if: inputs.store
        uses: actions/upload-artifact@v4
        with:
          name: sourcemaps
          path: |
            public/build/**/*.map
