name: Build and test

on:
  workflow_call:
        
jobs:
  ###########################
  # JUnit Test Report
  ###########################
  reporting:
    runs-on: ubuntu-latest
    name: Reporting
    if: success() || failure()

    steps:
      - name: Download results
        uses: actions/download-artifact@v4
        with:
          pattern: results-*
          path: results
          merge-multiple: true

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: results/junit/*.xml
