name: Build and test

on:
  workflow_call:
    inputs:
      php-versions:
        required: true
        type: string
      laravel-versions:
        required: true
        type: string
      default-php-version:
        required: true
        type: string
      default-laravel-version:
        required: true
        type: string
      project:
        required: true
        type: string
      organization:
        type: string
        default: monicahq
      node-version:
        required: true
        type: string
      matrix-exclude:
        type: string
        default: '[]'
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  tests:
    name: Unit tests
    uses: ./.github/workflows/test_library.yml
    with:
      php-version: ${{ matrix.php-version }}
      laravel-version: ${{ matrix.laravel-version }}
      coverage: ${{ matrix.laravel-version == inputs.default-laravel-version && matrix.php-version == inputs.default-php-version }}

    strategy:
      fail-fast: false
      matrix:
        php-version: ${{ fromJson(inputs.php-versions) }}
        laravel-version: ${{ fromJson(inputs.laravel-versions) }}
        exclude: ${{ fromJson(inputs.matrix-exclude) }}

  reporting:
    name: Reportings
    uses: ./.github/workflows/reporting.yml
    with:
      project: ${{ inputs.project }}
      organization: ${{ inputs.organization }}
      pattern: ${{ format('results_{0}_{1}*', inputs.default-php-version, inputs.default-laravel-version) }}
      sources: src
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    needs: tests
