name: Javascript linting

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '20'
      eslint:
        type: boolean
        default: true
      prettier:
        type: boolean
        default: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint vue and js files

    strategy:
      fail-fast: false

    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      # Yarn
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: yarn
      - name: Install yarn dependencies
        run: yarn install --immutable

      - name: Run eslint
        if: inputs.eslint
        run: yarn run lint --fix
      - name: Run prettier
        if: inputs.prettier
        run: yarn run format

      - name: Check if there is any file update needed
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            echo -e "Waiting modifications:\n$status"
            echo "::error::Eslint and prettier found fixes. Please run 'yarn run lint' and 'yarn run format' prior to your next commit."
            exit -1
          fi
