name: Static analysis

on:
  workflow_call:
    inputs:
      php-version:
        required: true
        type: string
      with:
        type: string
        default: psalm,phpstan

jobs:
  psalm:
    runs-on: ubuntu-latest
    name: Psalm
    if: contains(inputs.with, 'psalm')

    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - uses: monicahq/workflows/.github/actions/php@npm
        with:
          php-version: ${{ inputs.php-version }}
          coverage: none

      - uses: monicahq/workflows/.github/actions/composer@npm

      - name: Run psalm
        run: vendor/bin/psalm --output-format=github --php-version=${{ inputs.php-version }}

  phpstan:
    runs-on: ubuntu-latest
    name: PHPStan
    if: contains(inputs.with, 'phpstan')

    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - uses: monicahq/workflows/.github/actions/php@npm
        with:
          php-version: ${{ inputs.php-version }}
          coverage: none

      - uses: monicahq/workflows/.github/actions/composer@npm

      - name: Run phpstan
        run: vendor/bin/phpstan analyse
